apiVersion: v1
kind: Service
metadata:
  name: hairgen-web
  namespace: hairgen
  labels:
    app: hairgen-web
spec:
  type: NodePort
  selector:
    app: hairgen-web
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30320
      protocol: TCP
      name: http
